name: Tag Master

on:
  push:
    branches:
      - actions/config

permissions: write-all
  
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get current tag
        run: |
          git fetch --prune --unshallow
          echo "CURRENT_TAG=$(echo $(git describe --tags --abrev=0))"
      - name: Create new tag
        run: |
          echo $CURRENT_TAG 
          echo "NEXT_TAG=$(echo $CURRENT_TAG | awk  '{$NF += 1 ; print}')" >> "$GITHUB_ENV"